---
name: pre-commit action

description: pre-commit

runs:
  using: composite
  steps:
    - name: pre-commit
      uses: pre-commit/action@v3.0.1
      with:
        extra_args: -a --show-diff-on-failure
