---
name: Setup node.js action

description: Setup Node.js

runs:
  using: composite
  steps:
    - name: Setup Node.js (.node-version)
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version-file: .node-version
        cache: npm
