---
name: Setup node.js action

description: Setup Node.js

runs:
  using: composite
  steps:
    - name: Setup Node.js (.node-version)
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version-file: .node-version
        cache: npm
