---
name: Setup node.js action

description: Setup Node.js

runs:
  using: composite
  steps:
    - name: Setup Node.js (.node-version)
      uses: actions/setup-node@v6
      with:
        node-version-file: .node-version
        cache: npm
