---
name: Auto Assign Author

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  assign-author:
    name: Assign author
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Assign author
        uses: technote-space/assign-author@v1
