---
name: Auto Assign

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Auto Assign
        uses: kentaro-m/auto-assign-action@v1.2.3
        with:
          configuration-path: .github/auto_assign.yml
